kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  namespace: hsimoes-dev
  name: nodejs-image-demo
  labels:
    app: nodejs-image-demo
    app.kubernetes.io/component: nodejs-image-demo
    app.kubernetes.io/instance: nodejs-image-demo
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'nodejs-image-demo:v1.0'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:16-ubi8'
  source:
    type: Git
    git:
      uri: 'https://github.com/henri34000/nodejs-app.git'
  triggers:
    - type: ConfigChange
    - type: ImageChange
